2024-09-27 16:44:14,232	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 16:44:14,921	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7200
2024-09-27 16:44:15,132	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, 错误代码: 401, 返回内容: {'message': '接口访问源IP不在白名单', 'code': 11298, 'err_code': 40023002, 'trace_id': 'ccbdbdf38857335d9a8c58afb5549050'}, trace_id:ccbdbdf38857335d9a8c58afb5549050
2024-09-27 16:46:11,531	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 16:46:12,103	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7083
2024-09-27 16:46:12,301	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, 错误代码: 401, 返回内容: {'message': '接口访问源IP不在白名单', 'code': 11298, 'err_code': 40023002, 'trace_id': '8f9f6ad57d20fa97761a38e074849aa5'}, trace_id:8f9f6ad57d20fa97761a38e074849aa5
2024-09-27 16:47:09,420	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 16:47:10,002	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7025
2024-09-27 16:47:10,491	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-09-27 16:47:10,491	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-09-27 16:47:10,492	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-09-27 16:47:10,492	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-09-27 16:47:10,661	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-09-27 16:47:10,770	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「Aeolus的机器人-测试中」启动成功！
2024-09-27 16:47:10,770	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-09-27 16:47:10,771	[INFO]	(bot.py:18)on_ready	QQ群教学机器人 「Aeolus的机器人-测试中」 已启动!
2024-09-27 16:47:24,867	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  你好
2024-09-27 16:47:28,945	[ERROR]	(bot.py:78)on_group_at_message_create	调用API服务器失败: HTTPConnectionPool(host='localhost', port=6006): Max retries exceeded with url: /process_message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D6C1533AD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-09-27 16:54:32,677	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 16:54:33,423	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 6582
2024-09-27 16:54:34,056	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-09-27 16:54:34,057	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-09-27 16:54:34,057	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-09-27 16:54:34,057	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-09-27 16:54:34,196	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-09-27 16:54:34,345	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「Aeolus的机器人-测试中」启动成功！
2024-09-27 16:54:34,345	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-09-27 16:54:34,346	[INFO]	(bot.py:18)on_ready	QQ群教学机器人 「Aeolus的机器人-测试中」 已启动!
2024-09-27 16:54:46,911	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  你好
2024-09-27 18:21:54,632	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 18:21:55,570	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 1339
2024-09-27 18:21:56,064	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-09-27 18:21:56,065	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-09-27 18:21:56,065	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-09-27 18:21:56,066	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-09-27 18:21:56,225	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-09-27 18:21:56,333	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「Aeolus的机器人-测试中」启动成功！
2024-09-27 18:21:56,334	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-09-27 18:21:56,335	[INFO]	(bot.py:18)on_ready	QQ群教学机器人 「Aeolus的机器人-测试中」 已启动!
2024-09-27 18:22:10,398	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  你好
2024-09-27 18:22:12,516	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/F82C3D3F0013B930D66BAD8AADDEC34F/messages, 错误代码: 400, 返回内容: {'message': '请求数据异常', 'code': 40011000, 'err_code': 40011000, 'trace_id': 'a9040cda5cb5f40f9ffddc23b34b6cfc'}, trace_id:a9040cda5cb5f40f9ffddc23b34b6cfc
2024-09-27 18:34:15,841	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-09-27 18:34:16,503	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 599
2024-09-27 18:34:17,036	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-09-27 18:34:17,036	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-09-27 18:34:17,036	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-09-27 18:34:17,036	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-09-27 18:34:17,210	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-09-27 18:34:17,305	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「Aeolus的机器人-测试中」启动成功！
2024-09-27 18:34:17,306	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-09-27 18:34:17,306	[INFO]	(bot.py:18)on_ready	QQ群教学机器人 「Aeolus的机器人-测试中」 已启动!
2024-09-27 18:34:31,048	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  你好
2024-09-27 18:34:51,036	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  鲁迅和周树人是什么关系
2024-09-27 18:35:08,658	[INFO]	(bot.py:22)on_group_at_message_create	收到来自群 F82C3D3F0013B930D66BAD8AADDEC34F 的消息:  你可以帮我用python写一个快速排序吗
